apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pulse.fullname" . }}-collector
  namespace: {{ include "pulse.namespace" . }}
  labels:
    {{- include "pulse.labels" . | nindent 4 }}
    app.kubernetes.io/component: collector
spec:
  replicas: {{ .Values.collector.replicaCount }}
  selector:
    matchLabels:
      {{- include "pulse.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: collector
  template:
    metadata:
      labels:
        {{- include "pulse.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: collector
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: collector
          image: {{ .Values.global.imageRegistry | default "" }}{{- if .Values.global.imageRegistry }}/{{ end }}{{ .Values.collector.image.repository }}:{{ .Values.collector.image.tag }}
          imagePullPolicy: {{ .Values.collector.image.pullPolicy }}
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: pulse-postgres-creds
                  key: DATABASE_URL
            - name: PULSE_PRICING_PATH
              value: /etc/pulse/pricing.json
          ports:
            - name: traces
              containerPort: 9090
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9090
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            {{- toYaml .Values.collector.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
---
apiVersion: v1
kind: Service
metadata:
  name: pulse-collector
  namespace: {{ include "pulse.namespace" . }}
  labels:
    {{- include "pulse.labels" . | nindent 4 }}
    app.kubernetes.io/component: collector
spec:
  selector:
    {{- include "pulse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: collector
  ports:
    - name: traces
      port: 9090
      targetPort: 9090
