apiVersion: v1
kind: Service
metadata:
  name: {{ include "pulse.fullname" . }}-webhook-service
  namespace: {{ include "pulse.namespace" . }}
  labels:
    {{- include "pulse.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
spec:
  selector:
    {{- include "pulse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: operator
  ports:
    - name: webhook
      port: 443
      targetPort: 9443
