// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type captureConnInfo struct {
	_         structs.HostLayout
	DstIp     uint32
	DstPort   uint16
	_         [2]byte
	ConnectTs uint64
}

type captureConnKey struct {
	_   structs.HostLayout
	Pid uint32
	Fd  uint32
}

type captureConnectArgs struct {
	_           structs.HostLayout
	SockaddrPtr uint64
	Fd          uint32
	_           [4]byte
}

type captureReadArgs struct {
	_      structs.HostLayout
	BufPtr uint64
	Fd     uint32
	_      [4]byte
}

// loadCapture returns the embedded CollectionSpec for capture.
func loadCapture() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CaptureBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load capture: %w", err)
	}

	return spec, err
}

// loadCaptureObjects loads capture and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*captureObjects
//	*capturePrograms
//	*captureMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadCaptureObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadCapture()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// captureSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type captureSpecs struct {
	captureProgramSpecs
	captureMapSpecs
	captureVariableSpecs
}

// captureProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type captureProgramSpecs struct {
	TraceCloseEnter   *ebpf.ProgramSpec `ebpf:"trace_close_enter"`
	TraceConnectEnter *ebpf.ProgramSpec `ebpf:"trace_connect_enter"`
	TraceConnectExit  *ebpf.ProgramSpec `ebpf:"trace_connect_exit"`
	TraceReadEnter    *ebpf.ProgramSpec `ebpf:"trace_read_enter"`
	TraceReadExit     *ebpf.ProgramSpec `ebpf:"trace_read_exit"`
	TraceWriteEnter   *ebpf.ProgramSpec `ebpf:"trace_write_enter"`
}

// captureMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type captureMapSpecs struct {
	ActiveConnects *ebpf.MapSpec `ebpf:"active_connects"`
	ActiveReads    *ebpf.MapSpec `ebpf:"active_reads"`
	Events         *ebpf.MapSpec `ebpf:"events"`
	TargetPorts    *ebpf.MapSpec `ebpf:"target_ports"`
	TrackedConns   *ebpf.MapSpec `ebpf:"tracked_conns"`
}

// captureVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type captureVariableSpecs struct {
}

// captureObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadCaptureObjects or ebpf.CollectionSpec.LoadAndAssign.
type captureObjects struct {
	capturePrograms
	captureMaps
	captureVariables
}

func (o *captureObjects) Close() error {
	return _CaptureClose(
		&o.capturePrograms,
		&o.captureMaps,
	)
}

// captureMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadCaptureObjects or ebpf.CollectionSpec.LoadAndAssign.
type captureMaps struct {
	ActiveConnects *ebpf.Map `ebpf:"active_connects"`
	ActiveReads    *ebpf.Map `ebpf:"active_reads"`
	Events         *ebpf.Map `ebpf:"events"`
	TargetPorts    *ebpf.Map `ebpf:"target_ports"`
	TrackedConns   *ebpf.Map `ebpf:"tracked_conns"`
}

func (m *captureMaps) Close() error {
	return _CaptureClose(
		m.ActiveConnects,
		m.ActiveReads,
		m.Events,
		m.TargetPorts,
		m.TrackedConns,
	)
}

// captureVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadCaptureObjects or ebpf.CollectionSpec.LoadAndAssign.
type captureVariables struct {
}

// capturePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadCaptureObjects or ebpf.CollectionSpec.LoadAndAssign.
type capturePrograms struct {
	TraceCloseEnter   *ebpf.Program `ebpf:"trace_close_enter"`
	TraceConnectEnter *ebpf.Program `ebpf:"trace_connect_enter"`
	TraceConnectExit  *ebpf.Program `ebpf:"trace_connect_exit"`
	TraceReadEnter    *ebpf.Program `ebpf:"trace_read_enter"`
	TraceReadExit     *ebpf.Program `ebpf:"trace_read_exit"`
	TraceWriteEnter   *ebpf.Program `ebpf:"trace_write_enter"`
}

func (p *capturePrograms) Close() error {
	return _CaptureClose(
		p.TraceCloseEnter,
		p.TraceConnectEnter,
		p.TraceConnectExit,
		p.TraceReadEnter,
		p.TraceReadExit,
		p.TraceWriteEnter,
	)
}

func _CaptureClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed capture_x86_bpfel.o
var _CaptureBytes []byte
